# Generated by Django 4.2 on 2025-05-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_department_appointment_diagnosis_and_more"),
    ]

    operations = []
