# Generated by Django 4.2 on 2025-04-27 17:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_verify",
            new_name="is_verified",
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Short biography or qualifications"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="clinic_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="years_experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nurseprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(
                blank=True, help_text="e.g. A+, O-, etc.", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="insurance_provider",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pharmacistprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pharmacistprofile",
            name="pharmacy_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pharmacistprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in E.164 format, e.g. +14155552671",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\\\+?1?\\\\d{9,15}$",
                        "Enter a valid international phone number.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="practice_certificate",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="nurseprofile",
            name="shift",
            field=models.CharField(
                help_text="e.g. Day, Night, Rotational", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="insurance_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="pharmacistprofile",
            name="working_hours",
            field=models.CharField(help_text="e.g. Mon-Fri 9am-5pm", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
