# Generated by Django 4.2 on 2025-04-27 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_is_verify_user_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Combined first and last name",
                max_length=255,
                verbose_name="full name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in E.164 format, e.g. +14155552671",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$", "Enter a valid international phone number."
                    )
                ],
            ),
        ),
    ]
