# Generated by Django 4.2 on 2025-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_full_name_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile avatar image",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
