# Generated by Django 4.2 on 2025-05-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="allergies",
            field=models.TextField(blank=True, help_text="Known allergies"),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="medical_conditions",
            field=models.TextField(blank=True, help_text="Current medical conditions"),
        ),
    ]
