# Generated by Django 4.2 on 2025-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_patientprofile_allergies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="insurance_number",
            field=models.CharField(
                blank=True, help_text="Insurance policy number", max_length=50
            ),
        ),
    ]
