# Generated by Django 5.2.1 on 2025-05-14 19:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nurse Profile',
                'verbose_name_plural': 'Nurse Profiles',
            },
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_user_id', models.UUIDField(db_index=True)),
                ('nurse_user_id', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate_bpm', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate_bpm', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Vitals',
                'verbose_name_plural': 'Patient Vitals',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient_user_id', '-timestamp'], name='nurse_app_p_patient_e62b6f_idx'), models.Index(fields=['nurse_user_id', '-timestamp'], name='nurse_app_p_nurse_u_044b84_idx')],
            },
        ),
    ]
