# Generated by Django 5.1.5 on 2025-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
